# Generated by Django 6.1.1 on 2026-09-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0002_landlord_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='middle_name',
        ),
    ]
