# Generated by Django 6.1 on 2026-08-25 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20)),
                ('unit_type', models.CharField(choices=[('shop', 'Shop'), ('single', 'Single'), ('double_room', 'Double room'), ('bedsitter', 'Bedsitter'), ('one_bedroom', 'One bedroom'), ('two_bedroom', 'Two bedroom')], max_length=30)),
                ('unit_build', models.CharField(choices=[('mabati', 'Mabati'), ('block', 'Block')], default='block', max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='occupied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'ordering': ['-unit_number'],
            },
        ),
    ]
