# Generated by Django 6.1 on 2026-08-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('id_number', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.property')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='units.unit')),
            ],
            options={
                'ordering': ['-first_name'],
            },
        ),
    ]
