# Generated by Django 6.1 on 2026-08-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
