# Generated by Django 6.1 on 2026-08-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
