# Generated by Django 6.1 on 2026-09-05 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_property_name'),
        ('tenants', '0003_alter_tenant_phone'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='property_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='units.unit'),
        ),
    ]
