# Generated by Django 6.1.1 on 2026-09-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_property_obj_alter_tenant_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['property_obj']},
        ),
    ]
