# Generated by Django 6.1.1 on 2026-09-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('landlord', 'Landlord'), ('tenant', 'Tenant')], default='tenant', max_length=100),
        ),
    ]
