# Generated by Django 6.1.1 on 2026-09-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0006_alter_property_managers'),
        ('tenants', '0005_alter_tenant_options'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_snapshot', models.CharField(max_length=100)),
                ('entry_type', models.CharField(choices=[('charge', 'Rent Charge'), ('payment', 'Payment Received'), ('expense', 'Expense/Repair'), ('water', 'Water Bill'), ('deposit', 'Deposit'), ('adjustment', 'Correction')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='properties.property')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='ledger.ledgerentry')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='tenants.tenant')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='units.unit')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
