# Generated by Django 6.1.1 on 2026-09-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='managers',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='water_rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='Nairobi', max_length=150),
        ),
    ]
