# Generated by Django 6.1.1 on 2026-09-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_managers_property_water_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_name',
        ),
    ]
