# Generated by Django 6.1.1 on 2026-09-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_property_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='total_units',
        ),
    ]
