# Generated by Django 6.1.1 on 2026-09-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_total_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='managers',
            field=models.CharField(default='Winfam Properties', max_length=100, null=True),
        ),
    ]
