# Generated by Django 6.1 on 2026-08-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tenant_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
