# Generated by Django 6.1 on 2026-08-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_payment_tenant_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='completion',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='water',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('equity', 'Equity'), ('cash', 'Cash')], default='mpesa', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rent_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('overdue', 'Overdue'), ('vacant', 'Vacant'), ('caretaker', 'Caretaker'), ('paid_landlord', 'Paid Landlord')], default='overdue', max_length=50),
        ),
    ]
