# Generated by Django 6.1 on 2026-08-29 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_payment_date'),
        ('properties', '0002_property_property_name'),
        ('tenants', '0003_alter_tenant_phone'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('equity', 'Equity'), ('cash', 'Cash'), ('no_pay', 'No_pay')], default='mpesa', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='property_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='units.unit'),
        ),
    ]
