# Generated by Django 6.1 on 2026-09-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rent_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('overdue', 'Overdue'), ('vacant', 'Vacant'), ('caretaker', 'Caretaker'), ('pending', 'Pending'), ('paid_landlord', 'Paid Landlord')], default='overdue', max_length=50),
        ),
    ]
