# Generated by Django 6.1 on 2026-09-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_alter_payment_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='completion',
            field=models.CharField(choices=[('overdue', 'Overdue'), ('pending', 'Pending'), ('vacant', 'Vacant'), ('completed', 'Completed')], default='pending', max_length=100, null=True),
        ),
    ]
