# Generated by Django 6.1 on 2026-09-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_alter_payment_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilities',
            name='property_obj',
        ),
        migrations.RemoveField(
            model_name='utilities',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.DeleteModel(
            name='Utilities',
        ),
    ]
