# Generated by Django 6.1.1 on 2026-09-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0009_remove_utilities_property_obj_remove_utilities_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date']},
        ),
    ]
