# Generated by Django 6.1.1 on 2026-09-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_managers'),
        ('units', '0001_initial'),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilities',
            new_name='Utility',
        ),
    ]
