# Generated by Django 6.1.1 on 2026-09-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_rename_utilities_utility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='item',
            field=models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity')], default='water', max_length=100),
        ),
    ]
